services:
  client:
    container_name: monet-client
    build:
      context: apps/client
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5173:4173
    depends_on:
      - core
    networks:
      - frontend

  core:
    container_name: monet-core
    build:
      context: apps/core
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - frontend
      - backend
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: monet-mongodb
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - 27017:27017
    networks:
      - backend
    volumes:
      - database-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

networks:
  frontend:
    name: frontend-network
  backend:
    name: backend-network

volumes:
  database-data:
    driver: local
