services:
  core:
    container_name: monet-core
    build:
      context: apps/core
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - backend-network

networks:
  backend:
    name: backend-network
